### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by ScreamingHawk** [ScreamingHawk/evaporating-link#3]
Needs favicon

**Comment by ScreamingHawk** [comment]
I'm thinking something similar to the glass on the error page, but am opening to ideas

![Glass](http://evaporating.link/img/glass.svg)

**Comment by SaltyFingers1** [comment]
Hey, you're still interested in an favicon? :-) 

For which site do you want to use it?

**Comment by ScreamingHawk** [comment]
@SaltyFingers1 yes please, link is in the project README

**Comment by arjunrawal4** [comment]
Is this still available?

**Comment by ScreamingHawk** [comment]
@arjunrawal4 Sorry, this has just been merged
